### PR TITLE
add support for recovery mode feature in piRa1n pull 5

### PR DESCRIPTION
**Pull request by JoeyEamigh**
https://github.com/raspberryenvoie/piRa1n/pull/5

### CODE REVIEW

**Comment by raspberryenvoie** [comment]
Could you remove `(Can take a minute to work)` in `html/index.php` on line 73 as you already said it can take up to 15s?
Sorry if I'm too picky!

**Comment by JoeyEamigh** [comment]
Yeah sure! I'll do that in a bit!

**Comment by JoeyEamigh** [comment]
Removed it! Ready for your merge if you are satasfied.

**Review by raspberryenvoie — COMMENTED** [review]
Just add an indent on line 90 in actions.php and on line 71 in index.php and we should be good to merge

**Comment by JoeyEamigh** [comment]
I wrote this all in nano so my bad on the indentation - anything else?

**Comment by raspberryenvoie** [comment]
No, thanks a lot :))

**Pull request merged**
